import { describe, expect, it } from "vitest";

import {
  eventIdFromSourceRef,
  parseTeamsVtt,
  speakersIn,
  teamsSegmentsToText,
  teamsSourceRef,
} from "./teams-transcript";

// -------------------------------------------------------------------
// The only part of the Teams import that can be tested without a tenant,
// a real meeting and a live token - which is exactly why it is pure and
// exported. Everything else in this feature needs all three.
//
// The samples below are the shape Graph actually returns, cue identifiers
// and CRLF included, because both are things a parser written against a
// tidied-up example silently fails on.
// -------------------------------------------------------------------

const TEAMS_VTT = [
  "WEBVTT",
  "",
  "b1e6f0c4-0000-0000-0000-000000000001/1",
  "00:00:03.150 --> 00:00:06.420",
  "<v Joshua Brazier>Morning everyone, shall we start.</v>",
  "",
  "b1e6f0c4-0000-0000-0000-000000000001/2",
  "00:00:06.500 --> 00:00:09.000",
  "<v Joshua Brazier>First item is the migration.</v>",
  "",
  "b1e6f0c4-0000-0000-0000-000000000001/3",
  "00:00:09.100 --> 00:00:12.750",
  "<v Louis Dodo>I applied it to production this morning.</v>",
  "",
].join("\r\n");

describe("parseTeamsVtt", () => {
  it("reads the speaker's real name out of the voice span", () => {
    // The entire point of importing from Teams rather than transcribing
    // ourselves. Azure can separate voices; only Teams knows whose they are.
    const segments = parseTeamsVtt(TEAMS_VTT);

    expect(segments.map((segment) => segment.speakerName)).toEqual(["Joshua Brazier", "Louis Dodo"]);
  });

  it("merges consecutive cues from the same person", () => {
    // Teams emits a cue every few seconds. Unmerged, a transcript is one
    // line per breath with the same name repeated down the page.
    const segments = parseTeamsVtt(TEAMS_VTT);

    expect(segments).toHaveLength(2);
    expect(segments[0].text).toBe("Morning everyone, shall we start. First item is the migration.");
  });

  it("extends the merged turn's end time to its last cue", () => {
    const segments = parseTeamsVtt(TEAMS_VTT);

    expect(segments[0].startMs).toBe(3_150);
    expect(segments[0].endMs).toBe(9_000);
  });

  it("survives CRLF line endings, which is what Graph actually sends", () => {
    // Splitting a CRLF file on "\n" leaves a carriage return on every line.
    // It is invisible in a log and it breaks every regex in the parser.
    expect(parseTeamsVtt(TEAMS_VTT.replace(/\r\n/g, "\n"))).toEqual(parseTeamsVtt(TEAMS_VTT));
  });

  it("handles the cue identifier line Teams puts before the timing", () => {
    // A parser assuming the timing is the first line of a block drops every
    // single cue and returns an empty transcript that looks like an empty
    // meeting.
    expect(parseTeamsVtt(TEAMS_VTT).length).toBeGreaterThan(0);
  });

  it("parses timings with the hours field omitted", () => {
    const short = ["WEBVTT", "", "01:05.500 --> 01:08.000", "<v Sam>Under an hour.</v>"].join("\n");

    expect(parseTeamsVtt(short)[0].startMs).toBe(65_500);
  });

  it("reads a fraction as a fraction, not a count", () => {
    // "5" is 500ms. Parsed directly it would be 5ms, putting every cue in
    // very nearly the right place - which is the worst kind of wrong.
    const coarse = ["WEBVTT", "", "00:00:01.5 --> 00:00:02.0", "<v Sam>Half.</v>"].join("\n");

    expect(parseTeamsVtt(coarse)[0].startMs).toBe(1_500);
  });

  it("keeps cues that carry no speaker, without inventing one", () => {
    const anonymous = ["WEBVTT", "", "00:00:01.000 --> 00:00:02.000", "Somebody said this."].join("\n");
    const segments = parseTeamsVtt(anonymous);

    expect(segments).toHaveLength(1);
    expect(segments[0].speakerName).toBeNull();
    expect(segments[0].text).toBe("Somebody said this.");
  });

  it("never fills in Azure's numeric speaker field", () => {
    // Two different kinds of certainty. A number means "a voice we told
    // apart but cannot name"; putting one here would imply a guess where
    // there is an actual identity.
    for (const segment of parseTeamsVtt(TEAMS_VTT)) {
      expect(segment.speaker).toBeNull();
    }
  });

  it("skips headers, notes and style blocks", () => {
    const noisy = [
      "WEBVTT",
      "",
      "NOTE this file was generated by Teams",
      "",
      "STYLE",
      "::cue { color: white }",
      "",
      "00:00:01.000 --> 00:00:02.000",
      "<v Sam>Only this is a cue.</v>",
    ].join("\n");

    expect(parseTeamsVtt(noisy)).toHaveLength(1);
  });

  it("strips formatting tags rather than showing them as text", () => {
    const styled = [
      "WEBVTT",
      "",
      "00:00:01.000 --> 00:00:02.000",
      "<v Sam>That is <i>very</i> important.</v>",
    ].join("\n");

    expect(parseTeamsVtt(styled)[0].text).toBe("That is very important.");
  });

  it("returns nothing for an empty or header-only file, rather than throwing", () => {
    // A meeting where nobody spoke, or a transcript still being generated.
    // The caller turns an empty result into a clear message; an exception
    // would surface as a failed import.
    expect(parseTeamsVtt("")).toEqual([]);
    expect(parseTeamsVtt("WEBVTT\n\n")).toEqual([]);
  });
});

describe("teamsSegmentsToText", () => {
  it("labels each turn with the person's name", () => {
    const text = teamsSegmentsToText(parseTeamsVtt(TEAMS_VTT));

    expect(text).toBe(
      "Joshua Brazier: Morning everyone, shall we start. First item is the migration.\n\nLouis Dodo: I applied it to production this morning.",
    );
  });

  it("leaves an unattributed turn unlabelled", () => {
    const text = teamsSegmentsToText([
      { speaker: null, speakerName: null, startMs: 0, endMs: 1_000, text: "No name." },
    ]);

    expect(text).toBe("No name.");
  });
});

describe("speakersIn", () => {
  it("lists everyone once, in the order they first spoke", () => {
    expect(speakersIn(parseTeamsVtt(TEAMS_VTT))).toEqual(["Joshua Brazier", "Louis Dodo"]);
  });

  it("ignores turns with no name", () => {
    expect(
      speakersIn([{ speaker: null, speakerName: null, startMs: 0, endMs: 1, text: "x" }]),
    ).toEqual([]);
  });
});

describe("teamsSourceRef", () => {
  it("round-trips the event id back out", () => {
    // The whole "already imported" marker is this round trip: the list has
    // event ids and the rows hold source refs, and one has to find the other.
    const ref = teamsSourceRef("AAMkAGI2", "MSMjMCMjZGM");

    expect(eventIdFromSourceRef(ref)).toBe("AAMkAGI2");
  });

  it("distinguishes two transcripts of the same meeting", () => {
    // Teams produces a second transcript when a meeting is stopped and
    // restarted. On the event id alone they would collide and the newer one
    // could never be imported.
    expect(teamsSourceRef("event", "first")).not.toBe(teamsSourceRef("event", "second"));
  });

  it("reads a value with no separator whole rather than as nothing", () => {
    // A shape written before this format existed. Returning "" would quietly
    // stop matching rows that are perfectly fine.
    expect(eventIdFromSourceRef("just-an-id")).toBe("just-an-id");
  });

  it("keeps the event id when the transcript id is empty", () => {
    expect(eventIdFromSourceRef(teamsSourceRef("event", ""))).toBe("event");
  });
});
