import { describe, expect, it } from "vitest";

import {
  eventIdFromSourceRef,
  parseTeamsVtt,
  speakersIn,
  teamsSegmentsToText,
  teamsSourceRef,
} from "./teams-transcript";

// -------------------------------------------------------------------
// The only part of the Teams import that can be tested without a tenant,
// a real meeting and a live token - which is exactly why it is pure and
// exported. Everything else in this feature needs all three.
//
// The samples below are the shape Graph actually returns, cue identifiers
// and CRLF included, because both are things a parser written against a
// tidied-up example silently fails on.
// -------------------------------------------------------------------

const TEAMS_VTT = [
  "WEBVTT",
  "",
  "b1e6f0c4-0000-0000-0000-000000000001/1",
  "00:00:03.150 --> 00:00:06.420",
  "<v Joshua Brazier>Morning everyone, shall we start.</v>",
  "",
  "b1e6f0c4-0000-0000-0000-000000000001/2",
  "00:00:06.500 --> 00:00:09.000",
  "<v Joshua Brazier>First item is the migration.</v>",
  "",
  "b1e6f0c4-0000-0000-0000-000000000001/3",
  "00:00:09.100 --> 00:00:12.750",
  "<v Louis Dodo>I applied it to production this morning.</v>",
  "",
].join("\r\n");

describe("parseTeamsVtt", () => {
  it("reads the speaker's real name out of the voice span", () => {
    // The entire point of importing from Teams rather than transcribing
    // ourselves. Azure can separate voices; only Teams knows whose they are.
    const segments = parseTeamsVtt(TEAMS_VTT);

    expect(segments.map((segment) => segment.speakerName)).toEqual(["Joshua Brazier", "Louis Dodo"]);
  });

  it("merges consecutive cues from the same person", () => {
    // Teams emits a cue every few seconds. Unmerged, a transcript is one
    // line per breath with the same name repeated down the page.
    const segments = parseTeamsVtt(TEAMS_VTT);

    expect(segments).toHaveLength(2);
    expect(segments[0].text).toBe("Morning everyone, shall we start. First item is the migration.");
  });

  it("extends the merged turn's end time to its last cue", () => {
    const segments = parseTeamsVtt(TEAMS_VTT);

    expect(segments[0].startMs).toBe(3_150);
    expect(segments[0].endMs).toBe(9_000);
  });

  it("survives CRLF line endings, which is what Graph actually sends", () => {
    // Splitting a CRLF file on "\n" leaves a carriage return on every line.
    // It is invisible in a log and it breaks every regex in the parser.
    expect(parseTeamsVtt(TEAMS_VTT.replace(/\r\n/g, "\n"))).toEqual(parseTeamsVtt(TEAMS_VTT));
  });

  it("handles the cue identifier line Teams puts before the timing", () => {
    // A parser assuming the timing is the first line of a block drops every
    // single cue and returns an empty transcript that looks like an empty
    // meeting.
    expect(parseTeamsVtt(TEAMS_VTT).length).toBeGreaterThan(0);
  });

  it("parses timings with the hours field omitted", () => {
    const short = ["WEBVTT", "", "01:05.500 --> 01:08.000", "<v Sam>Under an hour.</v>"].join("\n");

    expect(parseTeamsVtt(short)[0].startMs).toBe(65_500);
  });

  it("reads a fraction as a fraction, not a count", () => {
    // "5" is 500ms. Parsed directly it would be 5ms, putting every cue in
    // very nearly the right place - which is the worst kind of wrong.
    const coarse = ["WEBVTT", "", "00:00:01.5 --> 00:00:02.0", "<v Sam>Half.</v>"].join("\n");

    expect(parseTeamsVtt(coarse)[0].startMs).toBe(1_500);
  });

  it("keeps cues that carry no speaker, without inventing one", () => {
    const anonymous = ["WEBVTT", "", "00:00:01.000 --> 00:00:02.000", "Somebody said this."].join("\n");
    const segments = parseTeamsVtt(anonymous);

    expect(segments).toHaveLength(1);
    expect(segments[0].speakerName).toBeNull();
    expect(segments[0].text).toBe("Somebody said this.");
  });

  it("never fills in Azure's numeric speaker field", () => {
    // Two different kinds of certainty. A number means "a voice we told
    // apart but cannot name"; putting one here would imply a guess where
    // there is an actual identity.
    for (const segment of parseTeamsVtt(TEAMS_VTT)) {
      expect(segment.speaker).toBeNull();
    }
  });

  it("skips headers, notes and style blocks", () => {
    const noisy = [
      "WEBVTT",
      "",
      "NOTE this file was generated by Teams",
      "",
      "STYLE",
      "::cue { color: white }",
      "",
      "00:00:01.000 --> 00:00:02.000",
      "<v Sam>Only this is a cue.</v>",
    ].join("\n");

    expect(parseTeamsVtt(noisy)).toHaveLength(1);
  });

  it("strips formatting tags rather than showing them as text", () => {
    const styled = [
      "WEBVTT",
      "",
      "00:00:01.000 --> 00:00:02.000",
      "<v Sam>That is <i>very</i> important.</v>",
    ].join("\n");

    expect(parseTeamsVtt(styled)[0].text).toBe("That is very important.");
  });

  it("returns nothing for an empty or header-only file, rather than throwing", () => {
    // A meeting where nobody spoke, or a transcript still being generated.
    // The caller turns an empty result into a clear message; an exception
    // would surface as a failed import.
    expect(parseTeamsVtt("")).toEqual([]);
    expect(parseTeamsVtt("WEBVTT\n\n")).toEqual([]);
  });
});

// -------------------------------------------------------------------
// Shapes Microsoft's own documentation shows and an obvious parser does not
// survive. Every one of these failed silently before it was handled: the cue
// was dropped, and because consecutive same-speaker cues merge afterwards,
// the result read as a perfectly ordinary transcript that was simply missing
// something. That is the failure mode worth the most tests.
// -------------------------------------------------------------------
describe("parseTeamsVtt, shapes that used to be dropped silently", () => {
  it("keeps a cue whose offset is NEGATIVE, clamped to the start", () => {
    // Microsoft: "Negative offsets indicate that the transcription began
    // while the conversation was ongoing." In other words, every meeting
    // where somebody pressed transcribe a minute late. Dropping these loses
    // the opening of the meeting and nothing says so.
    const late = [
      "WEBVTT",
      "",
      "-00:00:05.223 --> 00:00:02.100",
      "<v Joshua Brazier>We were already talking about the migration.</v>",
      "",
      "00:00:02.200 --> 00:00:04.000",
      "<v Louis Dodo>Right, and it is applied.</v>",
    ].join("\n");

    const segments = parseTeamsVtt(late);

    expect(segments).toHaveLength(2);
    expect(segments[0].text).toBe("We were already talking about the migration.");
    // Clamped rather than negated: an offset into a recording has no meaning
    // below zero, and a negative value would sort before the meeting began.
    expect(segments[0].startMs).toBe(0);
    expect(segments[0].endMs).toBe(2_100);
  });

  it("reads the first turn when WEBVTT is glued to it with no blank line", () => {
    // Microsoft's own examples do exactly this. Testing lines[0] for a header
    // before looking for a timing line would throw away the whole block - the
    // first speaker turn of every meeting.
    const glued = ["WEBVTT", "00:00:01.000 --> 00:00:03.000", "<v Sam>The very first thing said.</v>"].join(
      "\n",
    );

    const segments = parseTeamsVtt(glued);

    expect(segments).toHaveLength(1);
    expect(segments[0].text).toBe("The very first thing said.");
    expect(segments[0].speakerName).toBe("Sam");
  });

  it("splits a cue carrying two voice spans instead of merging two people", () => {
    // The worst failure this feature can have: one turn containing two
    // people's words, attributed entirely to whoever spoke first. A
    // transcript confidently wrong about who said something is worse than one
    // that says nothing.
    const shared = [
      "WEBVTT",
      "",
      "00:00:01.000 --> 00:00:04.000",
      "<v Joshua Brazier>Are we agreed?</v><v Louis Dodo>Agreed.</v>",
    ].join("\n");

    const segments = parseTeamsVtt(shared);

    expect(segments).toHaveLength(2);
    expect(segments.map((segment) => segment.speakerName)).toEqual(["Joshua Brazier", "Louis Dodo"]);
    expect(segments[1].text).toBe("Agreed.");
  });

  it("keeps the name on a classed voice tag", () => {
    // <v.loud Sam> is legal WebVTT. Without tolerating the class the turn
    // survives but loses its name, which is the one thing this whole feature
    // exists for.
    const classed = ["WEBVTT", "", "00:00:01.000 --> 00:00:02.000", "<v.loud Sam>Over here.</v>"].join("\n");

    expect(parseTeamsVtt(classed)[0].speakerName).toBe("Sam");
  });

  it("parses a single-digit seconds field", () => {
    const terse = ["WEBVTT", "", "00:00:1.5 --> 00:00:2.0", "<v Sam>Brief.</v>"].join("\n");

    expect(parseTeamsVtt(terse)[0].startMs).toBe(1_500);
  });

  it("still skips NOTE and STYLE blocks now that headers are not matched first", () => {
    // The header check moved AFTER the timing search, so this guards the
    // thing that change could have broken.
    const noisy = [
      "WEBVTT",
      "",
      "NOTE 00:00:01.000 --> 00:00:02.000 looks like a cue but is a note",
      "",
      "STYLE",
      "::cue { color: white }",
      "",
      "00:00:05.000 --> 00:00:06.000",
      "<v Sam>Only this is a cue.</v>",
    ].join("\n");

    const segments = parseTeamsVtt(noisy);

    expect(segments).toHaveLength(1);
    expect(segments[0].text).toBe("Only this is a cue.");
  });

  it("does not merge two people who each speak twice in a row", () => {
    // Guards the merge rule against the multi-span change: merging is by
    // speaker name, and the split must not let a second span join a previous
    // turn from a different person.
    const alternating = [
      "WEBVTT",
      "",
      "00:00:01.000 --> 00:00:02.000",
      "<v A>One.</v><v B>Two.</v>",
      "",
      "00:00:02.000 --> 00:00:03.000",
      "<v B>Three.</v>",
    ].join("\n");

    const segments = parseTeamsVtt(alternating);

    expect(segments.map((segment) => segment.speakerName)).toEqual(["A", "B"]);
    expect(segments[1].text).toBe("Two. Three.");
  });
});

describe("teamsSegmentsToText", () => {
  it("labels each turn with the person's name", () => {
    const text = teamsSegmentsToText(parseTeamsVtt(TEAMS_VTT));

    expect(text).toBe(
      "Joshua Brazier: Morning everyone, shall we start. First item is the migration.\n\nLouis Dodo: I applied it to production this morning.",
    );
  });

  it("leaves an unattributed turn unlabelled", () => {
    const text = teamsSegmentsToText([
      { speaker: null, speakerName: null, startMs: 0, endMs: 1_000, text: "No name." },
    ]);

    expect(text).toBe("No name.");
  });
});

describe("speakersIn", () => {
  it("lists everyone once, in the order they first spoke", () => {
    expect(speakersIn(parseTeamsVtt(TEAMS_VTT))).toEqual(["Joshua Brazier", "Louis Dodo"]);
  });

  it("ignores turns with no name", () => {
    expect(
      speakersIn([{ speaker: null, speakerName: null, startMs: 0, endMs: 1, text: "x" }]),
    ).toEqual([]);
  });
});

describe("teamsSourceRef", () => {
  it("round-trips the event id back out", () => {
    // The whole "already imported" marker is this round trip: the list has
    // event ids and the rows hold source refs, and one has to find the other.
    const ref = teamsSourceRef("AAMkAGI2", "MSMjMCMjZGM");

    expect(eventIdFromSourceRef(ref)).toBe("AAMkAGI2");
  });

  it("distinguishes two transcripts of the same meeting", () => {
    // Teams produces a second transcript when a meeting is stopped and
    // restarted. On the event id alone they would collide and the newer one
    // could never be imported.
    expect(teamsSourceRef("event", "first")).not.toBe(teamsSourceRef("event", "second"));
  });

  it("reads a value with no separator whole rather than as nothing", () => {
    // A shape written before this format existed. Returning "" would quietly
    // stop matching rows that are perfectly fine.
    expect(eventIdFromSourceRef("just-an-id")).toBe("just-an-id");
  });

  it("keeps the event id when the transcript id is empty", () => {
    expect(eventIdFromSourceRef(teamsSourceRef("event", ""))).toBe("event");
  });
});
